#!/usr/bin/env python3
"""
Generate the e-ink Mandelbrot splash as:
  - epd_fractal_splash.h  (1bpp PROGMEM for Adafruit drawBitmap)
  - assets/epd_fractal_splash.png (preview)

Adafruit GFX: each byte is 8 horizontal pixels, MSB = leftmost; 1 = ink.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from epd_fractal import mandelbrot_ink

WIDTH = 128
HEIGHT = 296


def pack_bitmap(width: int = WIDTH, height: int = HEIGHT) -> bytes:
	row_bytes = (width + 7) // 8
	out = bytearray(row_bytes * height)
	for py in range(height):
		for px in range(width):
			if mandelbrot_ink(px, py, width, height):
				byte_i = py * row_bytes + (px // 8)
				out[byte_i] |= 0x80 >> (px & 7)
	return bytes(out)


def write_header(path: Path, data: bytes, width: int, height: int) -> None:
	lines = [
		"/* Auto-generated by tools/pulse_monitor/gen_epd_fractal_splash.py",
		" * Do not edit by hand — re-run the generator to refresh.",
		" * 1bpp, MSB-left, Adafruit GFX drawBitmap format.",
		" */",
		"#ifndef RUSP_EPD_FRACTAL_SPLASH_H",
		"#define RUSP_EPD_FRACTAL_SPLASH_H",
		"",
		"#include <avr/pgmspace.h>",
		"#include <stdint.h>",
		"",
		f"#define EPD_FRACTAL_SPLASH_WIDTH  {width}",
		f"#define EPD_FRACTAL_SPLASH_HEIGHT {height}",
		"",
		f"const uint8_t EPD_FRACTAL_SPLASH[{len(data)}] PROGMEM = {{",
	]
	for i in range(0, len(data), 16):
		chunk = data[i : i + 16]
		hexes = ", ".join(f"0x{b:02X}" for b in chunk)
		comma = "," if i + 16 < len(data) else ""
		lines.append(f"\t{hexes}{comma}")
	lines += [
		"};",
		"",
		"#endif",
		"",
	]
	path.write_text("\n".join(lines))


def write_png(path: Path, data: bytes, width: int, height: int) -> None:
	try:
		from PIL import Image
	except ImportError as exc:
		raise SystemExit(
			"Pillow required for PNG preview: pip install Pillow"
		) from exc

	row_bytes = (width + 7) // 8
	img = Image.new("1", (width, height), 1)  # 1 = white in mode "1"
	px = img.load()
	for py in range(height):
		for x in range(width):
			bit = data[py * row_bytes + (x // 8)] & (0x80 >> (x & 7))
			px[x, py] = 0 if bit else 1  # 0 = black ink
	path.parent.mkdir(parents=True, exist_ok=True)
	img.save(path)


def main() -> None:
	parser = argparse.ArgumentParser(description=__doc__)
	root = Path(__file__).resolve().parents[2]
	parser.add_argument(
		"--header",
		type=Path,
		default=root / "epd_fractal_splash.h",
	)
	parser.add_argument(
		"--png",
		type=Path,
		default=root / "assets" / "epd_fractal_splash.png",
	)
	args = parser.parse_args()

	data = pack_bitmap()
	write_header(args.header, data, WIDTH, HEIGHT)
	write_png(args.png, data, WIDTH, HEIGHT)
	print(f"Wrote {args.header} ({len(data)} bytes)")
	print(f"Wrote {args.png}")


if __name__ == "__main__":
	main()
